### ISSUE TITLE
CommandError: Can't find msguniq. Make sure you have GNU gettext tools 0.15 or newer installed.

### ISSUE THREAD

**Issue by ang-ezm** [MrOrz/vscode-gettext#11]
Hi, 

I am using VS code on Windows 10 and when I perform the command: python manage.py makemessages -l 'pt_BR'    I get the error: CommandError: Can't find msguniq. Make sure you have GNU gettext tools 0.15 or newer installed.

The version I have installed in VS code is 0.1.1   
Is there a new version available to upgrade gettex?

Thanks!
Alberto

**Comment by MrOrz** [comment]
Hi @ang-ezm ,

vscode-gettext is just a syntax highlight & search plugin. Its implementation has nothing to do with gettext binary installed in your machine. Maybe you should consult django community, as you are using django commands, or try [StackOverflow](https://stackoverflow.com/questions/48911270/impossible-to-install-gettext-for-windows-10).

**Comment by ang-ezm** [comment]
Hi MrOrz!,  thank you for the information. I installed the gettext binary and is now working. Sorry about my confusion!...
All the best!
Alberto

**Comment by BOURKImohamed-GIT** [comment]
how you install it please,?

**Comment by mylal** [comment]
> Hi MrOrz!, thank you for the information. I installed the gettext binary and is now working. Sorry about my confusion!...
> All the best!
> Alberto

 Can't find msguniq. Make sure you have GNU gettext tools 0.15 or newer installed.
please suggest the solution of the link

**Comment by mylal** [comment]
Can't find msguniq. Make sure you have GNU gettext tools 0.15 or newer installed.
Anyone help me for this problem. how to install GNU gettext tools 0.15 newer installed

**Comment by dhiashalabi** [comment]
> how you install it please,?

You can try this if you are working in Windows.
[https://stackoverflow.com/a/53853244/11795918](url)
