### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by GitMensch** [MrOrz/vscode-gettext#12]
The [Open VSX Registry](https://open-vsx.org/?search=gettext) does not include any extensions yet. It is the default extension provider of free "vscode" builds and it would be good to find this extension there, too.

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by perrinjerome** [comment]
@MrOrz if you prefer we can also add this repository in https://github.com/open-vsx/publish-extensions and it will be published in OpenVSX automatically.

**Comment by MrOrz** [comment]
Hi @perrinjerome  and @GitMensch, thanks for the invitation! I have followed @perrinjerome 's advice and sent a pull request to open-vsx/publish-extensions here: https://github.com/open-vsx/publish-extensions/pull/406

Hope this is all the steps to make this available in Open VSX Registry :)

**Comment by GitMensch** [comment]
The CI build and publish is primarily intended to publish if an author cannot/don't want to publish themselves. Is this the case here? Otherwise please follow the [publish guide](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) and `ovsx publish`, or - if you prefer - use an [GitHub action](https://github.com/HaaLeo/publish-vscode-extension#readme) to publish via GitHub Action (then possibly directly to both OpenVSX and the MS market place).

**Comment by MrOrz** [comment]
> The CI build and publish is primarily intended to publish if an author cannot/don't want to publish themselves. Is this the case here? Otherwise please follow the [publish guide](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) and `ovsx publish`, or - if you prefer - use an [GitHub action](https://github.com/HaaLeo/publish-vscode-extension#readme) to publish via GitHub Action (then possibly directly to both OpenVSX and the MS market place).

I just took the path that sounds the easiest to me, that is, just firing one pull request :shipit: Publishing myself takes far more steps than the pull request.

**Comment by GitMensch** [comment]
Publishing via CI done, thanks for doing so.

Feel free to either close this one or keep it open if you consider to publish directly on any of the next releases (if done via CI a release only means tagging and it could be auto-published - once the registering steps are done with Open VSX Registry as it was done with the MS marketplace before; if not done then still `osvx` can be used to publish to both market places).

**Comment by geekley** [comment]
It's been a while since it didn't update to v0.2.1 on Open-VSX.

**Comment by GitMensch** [comment]
> It's been a while since it didn't update to v0.2.1 on Open-VSX.

This problem and this issue in general would be fixed by #27 (the PR may be linked to this issue to automatically be closed on merge).

**Comment by MrOrz** [comment]
Can verify that the latest versions can be published to Open VSX: https://open-vsx.org/extension/mrorz/language-gettext
