### ISSUE TITLE
How to auto select gettext as editor for .po files in vs code

### ISSUE THREAD

**Issue by EnriqueMata** [MrOrz/vscode-gettext#16]

**Comment by GitMensch** [comment]
This extension will be auto-enabled after install and as it contributes to the language id "gettext" with po, pot, pox in https://github.com/MrOrz/vscode-gettext/blob/4725dd5cb5ca1beabc1874cc2368cea9d9cb0aec/package.json#L22..L31 it will be loaded by default for those files, as long as no other extension does so. If other extensions are registered for those files with a different language extension you can change the one used with the "change language mode" command, if they use the same you have to deactivate the other one.

I guess this answers the question and the question-issue may be closed?

**Comment by MrOrz** [comment]
Thanks to @GitMensch for the answer.

@EnriqueMata please feel free to comment / re-open if your question is not resolved.
