### ISSUE TITLE
find/jump to next/previous fuzzy translation

### ISSUE THREAD

**Issue by GitMensch** [MrOrz/vscode-gettext#19]
Jump to untranslated messages was implemented with #7. It would be good to extend it to to jump to next/previous fuzzy string (the same approach can be used, but the attributes need to be included in the parsing of the message.

Note: there can be multiple attributes, those two are both fuzzy:

```po
#, fuzzy
#, fuzzy, c-format
```

_Originally posted by @GitMensch in https://github.com/MrOrz/vscode-gettext/issues/3#issuecomment-904327717_ - but that's actually a new request needing some code changes - so it is now moved out to a separate issue.
Feel free to assign to me and I'll have a look at implementing it (add parsing for `#,` `#|`, `#:` to the message, then check for fuzzy attribute in the new commands).

**Comment by MrOrz** [comment]
Sounds like a great feature! Thank you @GitMensch for the proposal and willing to take the task 🙏

**Comment by toku-sa-n** [comment]
Hi. This issue was created 2 years ago but it seems that nobody has implemented it. Can I do it and send a PR instead?

**Comment by GitMensch** [comment]
Yes, please give that a go.

**Comment by toku-sa-n** [comment]
Done in #28.
