### ISSUE TITLE
Finds / jumps to next / previous empty msgstr

### ISSUE THREAD

**Issue by MrOrz** [MrOrz/vscode-gettext#3]
- Lists / counts all empty `msgstr`
- Commands to jump to next / previous empty `msgstr`

**Comment by GitMensch** [comment]
This was shipped, at least with version 0.2.0, so I think the issue can either be closed. An extension to fuzzy strings would be nice, see #19.

**Comment by MrOrz** [comment]
Thanks, issues are linked now. Let's track the extension in #19 .
